version: '3.2'
services:
  memcache:
    image: memcached
    command: memcached -m 64
  storagon:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - build.version=${BUILD_VERSION:-local}
      args:
        - buildflag=clear_sourcecode
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/storagon/
      - media_volume:/var/www/storagon/media
    depends_on:
      - redis
      - memcache
      - mongodb
      - postgredb
    links:
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
    ports: [ "8000:8000" , "8889:8889"]
  mongodb:
    image: mongo:3.3.15
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: storagon
    volumes:
      - mongo_data:/data/db
  redis:
    restart: always
    image: "redis:alpine"
    command: redis-server --requirepass hanoi123
    expose:
      - '6379'
    ports:
      - "6379:6379"
  postgredb:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: storagon
      POSTGRES_USER: storagon_post
      POSTGRES_PASSWORD: 2Lj2UkqXymn6
      PG_SYSTEM_SHARED_BUFFERS: 256MB
      PG_SYSTEM_MAX_CONNECTIONS: 512
    ports: [ "5432:5432" ]
    command: "-c 'shared_buffers=256MB' -c 'max_connections=512'"
  nginx:
    build:
      context: .
      dockerfile: ./storagon/nginx/Dockerfile
    volumes:
      - ./static:/var/www/storagon/static
      - media_volume:/var/www/storagon/media
    ports: [ "80:80" ]
    links:
      - storagon:storagon
    depends_on:
      - storagon
  celery:
    build: .
    command: celery -A storagon -b redis://default:hanoi123@redis:6379/0 worker -l info --pidfile=
    volumes:
      - .:/var/www/storagon
    depends_on:
      - mongodb
      - postgredb
      - memcache
      - redis
    links:
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
    restart: always
  celery-beat:
    build: .
    command: celery -A storagon -b redis://default:hanoi123@redis:6379/0 beat -l info --pidfile=
    volumes:
      - .:/var/www/storagon
    depends_on:
      - mongodb
      - postgredb
      - memcache
      - redis
    links:
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
    restart: always
volumes:
  postgres_data:
  media_volume:
  mongo_data:
networks:
  default:
    external:
      name: storagon_default