version: '3.2'
services:
  storagon:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - build.version=${BUILD_VERSION:-local}
      args:
        - buildflag=clear_sourcecode
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/storagon/
      - media_volume:/var/www/storagon/media
    ports: [ "8000:8000" , "8889:8889"]
  mongodb:
    image: mongo:3.3.15
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGO_INITDB_DATABASE: storagon
    volumes:
      - mongo_data:/data/db
  rediscache:
    image: redis:alpine
  postgredb:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: storagon
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports: [ "5432:5432" ]
    command: "-c 'shared_buffers=256MB' -c 'max_connections=512'"
  nginx:
    build:
      context: .
      dockerfile: ./storagon/nginx/Dockerfile
    volumes:
      - ./static:/var/www/storagon/staticfiles
      - ./frontend:/var/www/storagon/frontend
      - media_volume:/var/www/storagon/media
    ports: [ "80:80" ]
    depends_on:
      - storagon

volumes:
  postgres_data:
  media_volume:
  mongo_data:
networks:
  default:
    external:
      name: storagon_default
