version: '3.5'
services:
  memcache:
    image: memcached
    restart: always
    command: memcached -m 64
    networks:
      - backend
  storagon:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - build.version=${BUILD_VERSION:-local}
      args:
        - buildflag=clear_sourcecode
    restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/storagon/
    depends_on:
      - memcache
      - redis
      - mongodb
      - postgredb
      - anisette
    links:
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
      - anisette:anisette
    networks:
      - backend
    ports: ["8889:8889"]
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: storagon
    ports:
      - 27017:27017
    networks:
      - backend
  redis:
    restart: always
    image: "redis:alpine"
    command: redis-server --requirepass hanoi123
    expose:
      - '6379'
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./storagon/redis/redis.conf:/etc/redis/redis.conf
  postgredb:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: storagon
      POSTGRES_USER: storagon_post
      POSTGRES_PASSWORD: 2Lj2UkqXymn6
      PG_SYSTEM_SHARED_BUFFERS: 256MB
      PG_SYSTEM_MAX_CONNECTIONS: 512
    networks:
      - backend
    ports: [ "5432:5432" ]
    command: "-c 'shared_buffers=256MB' -c 'max_connections=512'"
  nginx:
    build:
      context: .
      dockerfile: ./storagon/nginx/Dockerfile
    restart: always
    volumes:
      - .:/var/www/storagon
      - ./storagon/nginx/nginx.conf:/var/www/conf/nginx.conf:ro
    ports: [ "80:80", "8000:80" ]
    depends_on:
      - mongodb
      - postgredb
      - storagon
      - frontend
    links:
      - storagon:storagon
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
      - frontend:frontend
    networks:
      - backend

  frontend:
    build:
      context: ../fitviet-frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend

  anisette:
    image: dadoum/anisette-v3-server:latest
    container_name: anisette
    restart: always
    ports:
      - "6969:6969"
    volumes:
      - ./anisette_data:/home/Alcoholic/.config/anisette-v3:rw
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backend

  celery:
    build: .
    command: celery -A storagon -b redis://default:hanoi123@redis:6379/0 worker -l info --pidfile=
    volumes:
      - .:/var/www/storagon
    depends_on:
      - mongodb
      - postgredb
      - memcache
      - redis
    links:
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
    networks:
      - backend
    restart: always

  celery-beat:
    build: .
    command: celery -A storagon -b redis://default:hanoi123@redis:6379/0 beat -l info --pidfile=
    volumes:
      - .:/var/www/storagon
    depends_on:
      - mongodb
      - postgredb
      - memcache
      - redis
    links:
      - mongodb:mongodb
      - postgredb:postgredb
      - memcache:memcached
      - redis:redis
    networks:
      - backend
    restart: always
volumes:
  postgres_data:
  mongo_data:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge