# Generated by Django 3.2.6 on 2021-08-03 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import servermain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.PositiveSmallIntegerField(choices=[(0, 'credit'), (1, 'point'), (2, 'paypal'), (3, 'webmoney'), (4, 'ppd')], db_index=True, default=0)),
                ('amount', models.BigIntegerField(db_index=True, default=0)),
                ('account_id', models.CharField(db_index=True, default='', max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banlist',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('expires_date', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('enable', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bill_status', models.PositiveSmallIntegerField(choices=[(0, 'ok'), (1, 'cancel'), (2, 'fraud')], db_index=True, default=0)),
                ('paygate_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('plan_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('money_charged', models.BigIntegerField(db_index=True, default=0)),
                ('detail', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('folder_type', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'recycle')], db_index=True, default=0)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subFolderList', to='servermain.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_size', models.BigIntegerField(db_index=True, default=0)),
                ('file_hash', models.CharField(db_index=True, max_length=255)),
                ('file_location', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('server_status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'offline'), (2, 'downloadOnly')], db_index=True, default=0)),
                ('ip_address', models.CharField(db_index=True, max_length=255)),
                ('server_address', models.CharField(db_index=True, max_length=255)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('total_storage', models.BigIntegerField(db_index=True, default=0)),
                ('reserved_storage', models.BigIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_domain', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(0, 'user'), (1, 'affiliate'), (2, 'reseller'), (3, 'affiliatePPD')], db_index=True, default=0)),
                ('account_status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('storage_space', models.BigIntegerField(db_index=True, default=0)),
                ('plan_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('plan_expired', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2021, 8, 3, 15, 32, 37, 998011, tzinfo=utc))),
                ('eumk', models.CharField(blank=True, max_length=1024, null=True)),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('referer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refererList', to=settings.AUTH_USER_MODEL)),
                ('referer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referer2List', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('erfk', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_download_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('download_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('file_mode', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'premiumOnly'), (2, 'private')], db_index=True, default=0)),
                ('string_id', models.CharField(db_index=True, default=servermain.models.generateID, max_length=255)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fileList', to='servermain.folder')),
                ('realFile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servermain.realfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('apply_type', models.PositiveSmallIntegerField(choices=[(0, 'becomeAffiliate'), (1, 'payAffiliate'), (2, 'becomeAffiliatePPD'), (3, 'becomeAffiliatePPS')], db_index=True, default=0)),
                ('apply_status', models.PositiveSmallIntegerField(choices=[(0, 'processing'), (1, 'accepted'), (2, 'rejected')], db_index=True, default=0)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(0, 'agency'), (1, 'referer'), (2, 'website'), (3, 'pay'), (4, 'transfer'), (5, 'ppd'), (6, 'rebill'), (7, 'refererPPD')], db_index=True, default=0)),
                ('transaction_status', models.PositiveSmallIntegerField(choices=[(0, 'auto'), (1, 'manual'), (2, 'revert')], db_index=True, default=0)),
                ('amount', models.BigIntegerField(db_index=True, default=0)),
                ('data', models.TextField(blank=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.accountbalance')),
                ('invoice_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.bill')),
            ],
        ),
        migrations.AddField(
            model_name='realfile',
            name='serverFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servermain.serverfile'),
        ),
        migrations.CreateModel(
            name='PremiumKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('plan_id', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activated_date', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('activated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activatedPremiumKey', to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.bill')),
                ('reseller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resellPremiumKey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='userFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.userfile'),
        ),
    ]
