# Generated by Django 3.2.9 on 2022-09-03 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servermain', '0001_initial'),
    ]

    operations = [


        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'auto'), (1, 'manual'), (2, 'revert'), (3, 'success'), (4, 'pending'), (5, 'canceled')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'agency'), (1, 'referer'), (2, 'website'), (3, 'pay'), (4, 'transfer'), (5, 'ppd'), (6, 'rebill'), (7, 'refererPPD'), (8, 'deposit'), (9, 'withdrawn')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expired',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),

    ]
