# Generated by Django 3.2.18 on 2023-04-16 04:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servermain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCurrency',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(help_text='Required. 3 uppercase characters.', max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter a valid currency code.', 'invalid')], verbose_name='code')),
                ('label', models.CharField(max_length=16, verbose_name='label')),
                ('order_index', models.PositiveIntegerField(db_index=True, null=True, verbose_name='order_index')),
            ],
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='userFile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.userfile'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'auto'), (1, 'manual'), (2, 'revert'), (3, 'success'), (4, 'pending'), (5, 'canceled')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'agency'), (1, 'referer'), (2, 'website'), (3, 'pay'), (4, 'transfer'), (5, 'ppd'), (6, 'rebill'), (7, 'refererPPD'), (8, 'deposit'), (9, 'withdrawn')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expired',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CoinbaseCharges',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires_at')),
                ('charge_id', models.CharField(help_text='Required. 3 uppercase characters.', max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter a valid currency code.', 'invalid')], verbose_name='charge_id')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('usdt_address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='usdt_address')),
                ('usdc_address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='usdc_address')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'pending'), (2, 'completed'), (3, 'expired'), (4, 'unresolved'), (5, 'resolved'), (6, 'cancelled'), (7, 'pendingRefund'), (8, 'refunded')], db_index=True, default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.accountcurrency'),
        ),
        migrations.AddField(
            model_name='bill',
            name='coinbaseCharges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.coinbasecharges'),
        ),
    ]
