# Generated by Django 3.2.9 on 2022-09-03 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servermain', '0002_auto_20220903_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCurrency',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(help_text='Required. 3 uppercase characters.', max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter a valid currency code.', 'invalid')], verbose_name='code')),
                ('label', models.CharField(max_length=16, verbose_name='label')),
                ('order_index', models.PositiveIntegerField(db_index=True, null=True, verbose_name='order_index')),
            ],
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.accountcurrency'),
        ),
    ]
