# Generated by Django 3.2.9 on 2023-01-26 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servermain', '0003_auto_20220903_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='userFile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.userfile'),
        ),
        migrations.CreateModel(
            name='CoinbaseCharges',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires_at')),
                ('charge_id', models.CharField(help_text='Required. 3 uppercase characters.', max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter a valid currency code.', 'invalid')], verbose_name='charge_id')),
                ('label', models.CharField(max_length=16, verbose_name='label')),
                ('address', models.CharField(default='', max_length=255, verbose_name='address')),
                ('bill_status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'pending'), (2, 'completed'), (3, 'expired'), (4, 'unresolved'), (5, 'resolved'), (6, 'cancelled'), (7, 'pendingRefund'), (8, 'refunded')], db_index=True, default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='coinbaseCharges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servermain.coinbasecharges'),
        ),
    ]
