# Generated by Django 3.2.9 on 2023-01-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermain', '0004_auto_20230126_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinbasecharges',
            old_name='bill_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='coinbasecharges',
            name='address',
        ),
        migrations.RemoveField(
            model_name='coinbasecharges',
            name='label',
        ),
        migrations.AddField(
            model_name='coinbasecharges',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='coinbasecharges',
            name='usdc_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='usdc_address'),
        ),
        migrations.AddField(
            model_name='coinbasecharges',
            name='usdt_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='usdt_address'),
        ),
    ]
