# Generated by Django 3.2.6 on 2021-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, default='', max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateHTML',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, default='', max_length=511)),
            ],
        ),
    ]
