[uwsgi]
socket=127.0.0.1:8888
chdir=/home/TVA/storagon/
pythonpath=/home/TVA/storagon/
env DJANGO_SETTINGS_MODULE=storagon.settings
module=storagon.wsgi:application
master=True
processes=8
enable-threads=True
threads=4
setuid=1000 #set as user: TVA
setgid=1000 #set as user: TVA
harakiri=3600 #reject request more than 60 min
post-buffering = 104857600 # save to disk HTTP request more than 100MB
max-requests = 50000 #recycle process when in reach 50k requests
#limit-as=256
pidfile=/tmp/project-master2.pid
vacuum=True
daemonize=/home/TVA/log/uwsgi/uwsgi_storagon2.log