[uwsgi]
socket=127.0.0.1:8888
chdir=/vagrant
pythonpath=/vagrant/
env DJANGO_SETTINGS_MODULE=storagon.settings
module=storagon.wsgi:application
master=True
processes=2
enable-threads=True
#uid=1000 #local UID
#gid=2000
harakiri=600 #reject request more than 10 min
post-buffering = 1048576 # save to disk HTTP request more than 1MB
#limit-as=128
pidfile=/tmp/project-master2.pid
vacuum=True
max-requests=5000
python-autoreload = 1
;daemonize=/vagrant/log/uwsgi/vagrant2.log
