<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-09-03 10:27
=======
# Generated by Django 3.2.18 on 2023-04-16 04:48
>>>>>>> 8166b848ccff3196a5eb137d052be0a920cb48a5

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
<<<<<<< HEAD

=======
        migrations.CreateModel(
            name='AccountsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ssn', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.TextField(blank=True, null=True, verbose_name='signup_ip')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('used', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsdata_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_data_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsdata_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_data_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'AccountsData',
                'verbose_name_plural': 'AccountsData',
            },
        ),
        migrations.CreateModel(
            name='AccountsType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('default', models.BooleanField(db_index=True, default=False, verbose_name='default')),
            ],
            options={
                'verbose_name': 'AccountsType',
                'verbose_name_plural': 'AccountsType',
            },
        ),
        migrations.CreateModel(
            name='CheckerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_name')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id')),
                ('file_unique_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_unique_id')),
                ('file_size', models.BigIntegerField(db_index=True, default=0)),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('status_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='status_message_id')),
                ('document', models.FileField(upload_to='checker_documents/%Y/%m/%d/')),
                ('document_valid', models.FileField(blank=True, null=True, upload_to='checker_documents_valid/%Y/%m/%d/')),
                ('document_invalid', models.FileField(blank=True, null=True, upload_to='checker_documents_invalid/%Y/%m/%d/')),
                ('document_unknown', models.FileField(blank=True, null=True, upload_to='checker_documents_unknown/%Y/%m/%d/')),
                ('display_page_valid', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('display_page_invalid', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('display_page_unknown', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('total_value', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('display_value', models.PositiveSmallIntegerField(choices=[(0, 'valid'), (1, 'invalid'), (2, 'unknown')], db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'CheckerTask',
                'verbose_name_plural': 'CheckerTask',
            },
        ),
        migrations.CreateModel(
            name='CheckerType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'CheckerType',
                'verbose_name_plural': 'CheckerType',
            },
        ),
        migrations.CreateModel(
            name='CreatorType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'CreatorType',
                'verbose_name_plural': 'CreatorType',
            },
        ),
        migrations.CreateModel(
            name='KeysSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=25, unique=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'KeysSearch',
                'verbose_name_plural': 'KeysSearch',
            },
        ),
        migrations.CreateModel(
            name='MunAnti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('update_url', models.CharField(db_index=True, max_length=9999)),
            ],
            options={
                'verbose_name': 'MunAnti',
                'verbose_name_plural': 'MunAnti',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=512, verbose_name='label')),
                ('default', models.BooleanField(db_index=True, default=False, verbose_name='default')),
                ('logic_step', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'processing'), (3, 'completed'), (4, 'failed'), (5, 'checked')], db_index=True, default=0, verbose_name='logic_step')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('telegram_id', models.CharField(blank=True, max_length=255, verbose_name='telegram_id')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last_name')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='username')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checker_type', to='telegram_bot.checkertype')),
                ('creator_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_type', to='telegram_bot.creatortype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_telegram', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User_Telegram',
                'verbose_name_plural': 'User_Telegram',
            },
        ),
        migrations.CreateModel(
            name='UserHwid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hwid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreateFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_function', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheckFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_function', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MunProxies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('socks_port', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='socks_port')),
                ('control_port', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='control_port')),
                ('bridges_string', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='bridges_string')),
                ('rotating_time', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='rotating_time')),
                ('country_code', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='country_code')),
                ('country_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='country_name')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munproxies_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munproxies_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munproxies_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'MunProxies',
                'verbose_name_plural': 'MunProxies',
            },
        ),
        migrations.CreateModel(
            name='LinkCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('url', models.TextField(blank=True, default='', null=True, verbose_name='url')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkcheckout_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkcheckout_modified', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='link_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'LinkCheckout',
                'verbose_name_plural': 'LinkCheckout',
            },
        ),
        migrations.CreateModel(
            name='CheckerValid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('checker_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTaskCheckerValid', to='telegram_bot.checkertask')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerValid_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkervalid_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkervalid_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerValid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerValid',
                'verbose_name_plural': 'CheckerValid',
            },
        ),
        migrations.CreateModel(
            name='CheckerUnknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('checker_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTaskCheckerUnknown', to='telegram_bot.checkertask')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerUnknown_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerunknown_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerunknown_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerUnknown', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerUnknown',
                'verbose_name_plural': 'CheckerUnknown',
            },
        ),
        migrations.AddField(
            model_name='checkertask',
            name='checker_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTask_checker_type', to='telegram_bot.checkertype'),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkertask_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkertask_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerTask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckerInvalid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('checker_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTaskCheckerInvalid', to='telegram_bot.checkertask')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerInvalid_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerinvalid_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerinvalid_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerInvalid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerInvalid',
                'verbose_name_plural': 'CheckerInvalid',
            },
        ),
>>>>>>> 8166b848ccff3196a5eb137d052be0a920cb48a5
        migrations.CreateModel(
            name='BrowserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('profile_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_name')),
                ('profile_os', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_os')),
                ('profile_browser', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_browser')),
                ('profile_version', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_version')),
                ('profile_proxy_type', models.PositiveSmallIntegerField(choices=[(0, 'no_proxy'), (1, 'proxy'), (2, 'sock5')], db_index=True, default=2)),
                ('profile_proxy_details', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_proxy_details')),
<<<<<<< HEAD
=======
                ('profile_socks5_details', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_socks5_details')),
>>>>>>> 8166b848ccff3196a5eb137d052be0a920cb48a5
                ('profile_proxy_username', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_proxy_username')),
                ('profile_proxy_password', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_proxy_password')),
                ('profile_path_cookies', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_path_cookies')),
                ('profile_user_agent', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_user_agent')),
                ('profile_original_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_original_name')),
                ('profile_resolution', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_resolution')),
                ('profile_cpu', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_cpu')),
                ('profile_canvas', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_canvas')),
                ('profile_rects', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_rects')),
<<<<<<< HEAD
                ('profile_font', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_font')),
=======
                ('profile_font', models.TextField(blank=True, default='', null=True, verbose_name='profile_font')),
>>>>>>> 8166b848ccff3196a5eb137d052be0a920cb48a5
                ('profile_start_url', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_start_url')),
                ('profile_audio', models.TextField(blank=True, default='', null=True, verbose_name='profile_audio')),
                ('profile_webgl', models.TextField(blank=True, default='', null=True, verbose_name='profile_webgl')),
                ('profile_time_zone', models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'noise'), (2, 'follow')], db_index=True, default=2)),
                ('profile_webrtc', models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'noise'), (2, 'follow')], db_index=True, default=2)),
                ('profile_geo', models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'noise'), (2, 'follow')], db_index=True, default=2)),
                ('profile_vendor', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='vendor')),
                ('profile_renderer', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='renderer')),
                ('profile_note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('profile_status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'warning'), (2, 'block')], db_index=True, default=0)),
<<<<<<< HEAD
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_modified', to=settings.AUTH_USER_MODEL)),
=======
                ('profile_used', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_modified', to=settings.AUTH_USER_MODEL)),
>>>>>>> 8166b848ccff3196a5eb137d052be0a920cb48a5
                ('profile_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_profile_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='profile_owner')),
            ],
            options={
                'verbose_name': 'BrowserProfiles',
                'verbose_name_plural': 'BrowserProfiles',
            },
        ),
<<<<<<< HEAD

=======
        migrations.CreateModel(
            name='AccountsSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('warranty_date', models.DateTimeField(blank=True, null=True, verbose_name='warranty_date')),
                ('warranty', models.BooleanField(default=False, verbose_name='warranty')),
                ('ordered', models.BooleanField(default=False, verbose_name='ordered')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='ordered_date')),
                ('details', models.CharField(db_index=True, max_length=9999)),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('selling_status', models.PositiveSmallIntegerField(choices=[(0, 'listed'), (1, 'sold'), (2, 'block')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsselling_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsselling_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsSelling',
                'verbose_name_plural': 'AccountsSelling',
            },
        ),
        migrations.CreateModel(
            name='AccountsEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('proxy', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('socks5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_service', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('used', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('accounts_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_data_emails_set', to='telegram_bot.accountsdata', verbose_name='account_data')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsemails_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsemails_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsEmails',
                'verbose_name_plural': 'AccountsEmails',
            },
        ),
        migrations.AddField(
            model_name='accountsdata',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_data_type_set', to='telegram_bot.accountstype', verbose_name='type'),
        ),
        migrations.CreateModel(
            name='AccountsCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('proxy', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('socks5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('proxy_username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('proxy_password', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_service', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('viewed', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('auto_view', models.BooleanField(db_index=True, default=False, verbose_name='auto_view')),
                ('auto_viewed', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='auto_viewed')),
                ('accounts_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_data_created_set', to='telegram_bot.accountsdata', verbose_name='account_data')),
                ('accounts_emails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_set', to='telegram_bot.accountsemails', verbose_name='accounts_emails')),
                ('browser_profiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browser_profiles_set', to='telegram_bot.browserprofiles', verbose_name='browser_profiles')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountscreated_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountscreated_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsCreated',
                'verbose_name_plural': 'AccountsCreated',
            },
        ),
>>>>>>> 8166b848ccff3196a5eb137d052be0a920cb48a5
    ]
