# Generated by Django 3.2.9 on 2022-09-03 10:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='BrowserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('profile_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_name')),
                ('profile_os', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_os')),
                ('profile_browser', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_browser')),
                ('profile_version', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_version')),
                ('profile_proxy_type', models.PositiveSmallIntegerField(choices=[(0, 'no_proxy'), (1, 'proxy'), (2, 'sock5')], db_index=True, default=2)),
                ('profile_proxy_details', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_proxy_details')),
                ('profile_proxy_username', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_proxy_username')),
                ('profile_proxy_password', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_proxy_password')),
                ('profile_path_cookies', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_path_cookies')),
                ('profile_user_agent', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_user_agent')),
                ('profile_original_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_original_name')),
                ('profile_resolution', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_resolution')),
                ('profile_cpu', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_cpu')),
                ('profile_canvas', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_canvas')),
                ('profile_rects', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_rects')),
                ('profile_font', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_font')),
                ('profile_start_url', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_start_url')),
                ('profile_audio', models.TextField(blank=True, default='', null=True, verbose_name='profile_audio')),
                ('profile_webgl', models.TextField(blank=True, default='', null=True, verbose_name='profile_webgl')),
                ('profile_time_zone', models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'noise'), (2, 'follow')], db_index=True, default=2)),
                ('profile_webrtc', models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'noise'), (2, 'follow')], db_index=True, default=2)),
                ('profile_geo', models.PositiveSmallIntegerField(choices=[(0, 'block'), (1, 'noise'), (2, 'follow')], db_index=True, default=2)),
                ('profile_vendor', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='vendor')),
                ('profile_renderer', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='renderer')),
                ('profile_note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('profile_status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'warning'), (2, 'block')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_modified', to=settings.AUTH_USER_MODEL)),
                ('profile_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_profile_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='profile_owner')),
            ],
            options={
                'verbose_name': 'BrowserProfiles',
                'verbose_name_plural': 'BrowserProfiles',
            },
        ),

    ]
