# Generated by Django 3.2.9 on 2022-09-03 10:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('default', models.BooleanField(db_index=True, default=False, verbose_name='default')),
            ],
            options={
                'verbose_name': 'AccountsType',
                'verbose_name_plural': 'AccountsType',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=512, verbose_name='label')),
                ('default', models.BooleanField(db_index=True, default=False, verbose_name='default')),
                ('logic_step', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'processing'), (3, 'completed'), (4, 'failed'), (5, 'checked')], db_index=True, default=0, verbose_name='logic_step')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('telegram_id', models.CharField(blank=True, max_length=255, verbose_name='telegram_id')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last_name')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='username')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_telegram', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User_Telegram',
                'verbose_name_plural': 'User_Telegram',
            },
        ),
        migrations.CreateModel(
            name='AccountsSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('warranty_date', models.DateTimeField(blank=True, null=True, verbose_name='warranty_date')),
                ('warranty', models.BooleanField(default=False, verbose_name='warranty')),
                ('ordered', models.BooleanField(default=False, verbose_name='ordered')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='ordered_date')),
                ('details', models.CharField(db_index=True, max_length=9999)),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('selling_status', models.PositiveSmallIntegerField(choices=[(0, 'listed'), (1, 'sold'), (2, 'block')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsselling_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsselling_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsSelling',
                'verbose_name_plural': 'AccountsSelling',
            },
        ),
    ]
