# Generated by Django 3.2.9 on 2022-09-09 23:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0002_accountsselling_accountstype_status_usertelegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('fisrt_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ssn', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('used', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsdata_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_data_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsdata_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_data_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_data_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsData',
                'verbose_name_plural': 'AccountsData',
            },
        ),
        migrations.AddField(
            model_name='browserprofiles',
            name='profile_used',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='accountsselling',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsselling_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='browserprofiles',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browserprofiles_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountsEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('proxy', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('socks5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_service', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('used', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('accounts_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_data_emails_set', to='telegram_bot.accountsdata', verbose_name='account_data')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsemails_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountsemails_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsEmails',
                'verbose_name_plural': 'AccountsEmails',
            },
        ),
        migrations.CreateModel(
            name='AccountsCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('usernane', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('proxy', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('socks5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_service', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('viewed', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('account_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_email_set', to='telegram_bot.accountsemails', verbose_name='account_email')),
                ('accounts_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_data_created_set', to='telegram_bot.accountsdata', verbose_name='account_data')),
                ('browser_profiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browser_profiles_set', to='telegram_bot.browserprofiles', verbose_name='browser_profiles')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountscreated_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created_customer_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountscreated_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'AccountsCreated',
                'verbose_name_plural': 'AccountsCreated',
            },
        ),
    ]
