# Generated by Django 3.2.18 on 2026-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20260616_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscreated',
            name='subscription',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='subscription'),
        ),
        migrations.AddField(
            model_name='accountscreated',
            name='subscription_owner',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='subscription_owner'),
        ),
    ]
