# Generated by Django 3.2.9 on 2022-09-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_auto_20220910_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountscreated',
            name='account_email',
        ),
        migrations.AddField(
            model_name='accountscreated',
            name='accounts_emails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_emails_set', to='telegram_bot.accountsemails', verbose_name='accounts_emails'),
        ),
    ]
