# Generated by Django 3.2.9 on 2022-09-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_auto_20220910_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountscreated',
            old_name='usernane',
            new_name='username',
        ),
    ]
