# Generated by Django 3.2.9 on 2022-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_rename_usernane_accountscreated_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscreated',
            name='auto_view',
            field=models.BooleanField(db_index=True, default=False, verbose_name='auto_view'),
        ),
    ]
