# Generated by Django 3.2.9 on 2022-09-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_accountscreated_auto_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscreated',
            name='auto_viewed',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='auto_viewed'),
        ),
    ]
