# Generated by Django 3.2.9 on 2022-09-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_accountscreated_auto_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeysSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=25, unique=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'KeysSearch',
                'verbose_name_plural': 'KeysSearch',
            },
        ),
    ]
