# Generated by Django 3.2.9 on 2022-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_keyssearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='browserprofiles',
            name='profile_socks5_details',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='profile_socks5_details'),
        ),
    ]
