# Generated by Django 3.2.9 on 2022-10-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_browserprofiles_profile_socks5_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunAnti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('version', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('update_url', models.CharField(db_index=True, max_length=9999)),
            ],
            options={
                'verbose_name': 'MunAnti',
                'verbose_name_plural': 'MunAnti',
            },
        ),
        migrations.AddField(
            model_name='accountscreated',
            name='proxy_password',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountscreated',
            name='proxy_username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
