# Generated by Django 3.2.9 on 2022-11-02 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0010_auto_20221026_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunProxies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('socks_port', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='socks_port')),
                ('control_port', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='control_port')),
                ('bridges_string', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='bridges_string')),
                ('rotating_time', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='rotating_time')),
                ('country_code', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='country_code')),
                ('country_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='country_name')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munproxies_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munproxies_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munproxies_owner_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'MunProxies',
                'verbose_name_plural': 'MunProxies',
            },
        ),
    ]
