# Generated by Django 3.2.9 on 2022-11-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_munproxies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsdata',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
