# Generated by Django 3.2.9 on 2022-12-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_rename_fisrt_name_accountsdata_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsdata',
            name='signup_ip',
            field=models.CharField(blank=True, db_index=True, max_length=999, null=True),
        ),
    ]
