# Generated by Django 3.2.9 on 2022-12-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_alter_accountsdata_signup_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsdata',
            name='signup_ip',
            field=models.TextField(blank=True, null=True, verbose_name='signup_ip'),
        ),
    ]
