# Generated by Django 3.2.9 on 2022-12-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_alter_accountsdata_signup_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserprofiles',
            name='profile_font',
            field=models.TextField(blank=True, default='', null=True, verbose_name='profile_font'),
        ),
    ]
