# Generated by Django 3.2.9 on 2023-01-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0015_alter_browserprofiles_profile_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('url', models.TextField(blank=True, default='', null=True, verbose_name='url')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkcheckout_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkcheckout_modified', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='link_type_set', to='telegram_bot.accountstype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'LinkCheckout',
                'verbose_name_plural': 'LinkCheckout',
            },
        ),
    ]
