# Generated by Django 3.2.9 on 2023-01-09 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0016_linkcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHwid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hwid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreateFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_function', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheckFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_function', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
