# Generated by Django 3.2.9 on 2023-01-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0017_usercheckfunction_usercreatefunction_userhwid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'CheckerType',
                'verbose_name_plural': 'CheckerType',
            },
        ),
        migrations.CreateModel(
            name='CreatorType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='value')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'emailNotActivated'), (2, 'banned'), (3, 'temporary')], db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'CreatorType',
                'verbose_name_plural': 'CreatorType',
            },
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='checker_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checker_type', to='telegram_bot.checkertype'),
        ),
        migrations.AddField(
            model_name='usertelegram',
            name='creator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_type', to='telegram_bot.creatortype'),
        ),
    ]
