# Generated by Django 3.2.9 on 2023-01-15 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0018_auto_20230114_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_name')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id')),
                ('file_unique_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_unique_id')),
                ('file_size', models.BigIntegerField(db_index=True, default=0)),
                ('url', models.TextField(blank=True, default='', null=True, verbose_name='url')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='note')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed')], db_index=True, default=0)),
                ('document', models.FileField(upload_to='checker_documents/%Y/%m/%d/')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTask_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkertask_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkertask_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerTask', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerTask',
                'verbose_name_plural': 'CheckerTask',
            },
        ),
    ]
