# Generated by Django 3.2.9 on 2023-01-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0019_checkertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkertask',
            name='document_invalid',
            field=models.FileField(blank=True, null=True, upload_to='checker_documents_invalid/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='document_unknown',
            field=models.FileField(blank=True, null=True, upload_to='checker_documents_unknown/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='document_valid',
            field=models.FileField(blank=True, null=True, upload_to='checker_documents_valid/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='status_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status_message_id'),
        ),
        migrations.AlterField(
            model_name='checkertask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='linkcheckout',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0),
        ),
    ]
