# Generated by Django 3.2.9 on 2023-01-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0020_auto_20230116_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerValid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('checker_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTaskCheckerValid', to='telegram_bot.checkertask')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerValid_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkervalid_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkervalid_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerValid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerValid',
                'verbose_name_plural': 'CheckerValid',
            },
        ),
        migrations.CreateModel(
            name='CheckerUnknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('checker_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTaskCheckerUnknown', to='telegram_bot.checkertask')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerUnknown_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerunknown_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerunknown_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerUnknown', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerUnknown',
                'verbose_name_plural': 'CheckerUnknown',
            },
        ),
        migrations.CreateModel(
            name='CheckerInvalid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'working'), (1, 'completed'), (2, 'failed'), (3, 'suspended')], db_index=True, default=0)),
                ('checker_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerTaskCheckerInvalid', to='telegram_bot.checkertask')),
                ('checker_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CheckerInvalid_checker_type', to='telegram_bot.checkertype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerinvalid_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkerinvalid_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserCheckerInvalid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CheckerInvalid',
                'verbose_name_plural': 'CheckerInvalid',
            },
        ),
    ]
