# Generated by Django 3.2.9 on 2023-01-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0021_checkerinvalid_checkerunknown_checkervalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkerinvalid',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='checkertask',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='checkerunknown',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='checkervalid',
            old_name='user',
            new_name='owner',
        ),
    ]
