# Generated by Django 3.2.9 on 2023-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_auto_20230119_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkertask',
            name='url',
        ),
        migrations.AddField(
            model_name='checkertask',
            name='details',
            field=models.TextField(blank=True, default='', null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='display_page',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='display_value',
            field=models.PositiveSmallIntegerField(choices=[(0, 'valid'), (1, 'invalid'), (2, 'unknown')], db_index=True, default=0),
        ),
    ]
