# Generated by Django 3.2.9 on 2023-01-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0023_auto_20230119_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkertask',
            old_name='display_page',
            new_name='display_page_invalid',
        ),
        migrations.AddField(
            model_name='checkertask',
            name='display_page_valid',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='checkertask',
            name='total_value',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
    ]
