# Generated by Django 3.2.9 on 2023-01-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0024_auto_20230121_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkertask',
            name='display_page_unknown',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
    ]
