# Generated by Django 3.2.9 on 2023-01-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0025_checkertask_display_page_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkertask',
            name='total_value',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
