# Generated by Django 3.2.18 on 2026-06-18 19:20

from django.db import migrations, models

def convert_used_to_live(apps, schema_editor):
    Card = apps.get_model('cards_manager', 'Card')
    Card.objects.filter(status='Đã sử dụng').update(status='Thẻ sống')

class Migration(migrations.Migration):

    dependencies = [
        ('cards_manager', '0005_alter_card_status'),
    ]

    operations = [
        migrations.RunPython(convert_used_to_live),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(
                choices=[
                    ('Chưa sử dụng', 'Chưa sử dụng'),
                    ('Đang sử dụng', 'Đang sử dụng'),
                    ('Thẻ chết', 'Thẻ chết'),
                    ('Thẻ sống', 'Thẻ sống'),
                    ('Thẻ tốt', 'Thẻ tốt'),
                    ('Thẻ lỗi', 'Thẻ lỗi'),
                    ('Sub OK', 'Sub OK'),
                    ('Sub lỗi', 'Sub lỗi'),
                ],
                default='Chưa sử dụng',
                max_length=50
            ),
        ),
    ]
