# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/

# user  nginx;
worker_processes  2;
daemon off;

worker_rlimit_nofile 10240;
#worker_rlimit_sigpending 32768;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
error_log  /dev/stdout  crit;

#pid		logs/nginx.pid;


events {
	worker_connections  2048;
}


http {
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
					  '$status $body_bytes_sent "$http_referer" '
					  '"$http_user_agent" "$http_x_forwarded_for"';

	
	access_log  off;
    limit_conn_log_level info;
	
	log_format  xfs  '"$request"|$http_range|$remote_addr|$body_bytes_sent|$status';
    log_format  xfs_p  '$arg_id|$arg_usr|$remote_addr|$body_bytes_sent|$status';

	sendfile		on;
	#tcp_nopush	 on;

	reset_timedout_connection on;

    server_tokens off;
    autoindex off;

	keepalive_timeout  0;
	#keepalive_timeout  65;

	limit_conn_zone $binary_remote_addr zone=one:10m;
	
	#gzip  on;

	underscores_in_headers on;

    # this will resolve dns at runtime using docker dns
    resolver 127.0.0.11 valid=30s;

	server {
		listen	   80;
		server_name  localhost;
		client_max_body_size 100M;
		client_body_buffer_size 10M;

		proxy_set_header X_REAL_IP $remote_addr;
		proxy_pass_header SIGNATURE_AUTHORIZATION;
		
		#charset koi8-r;

		access_log /dev/stdout main;
		
		#redirect only serverfile request to uwsgi

		location @server_main_proxy {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_connect_timeout 5s;
            proxy_send_timeout   3s;
            proxy_read_timeout   30s;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # enable this if and only if you use HTTPS
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Host $http_host;
            # we don't want nginx trying to do something clever with
            # redirects, we set the Host: header above already.
            proxy_redirect off;

            set $upstream_name storagon;
            proxy_pass http://$upstream_name:8889;

            expires off;
			
        }

		location / {
			include uwsgi_params;
            uwsgi_pass storagon:8889;
			add_header Access-Control-Allow-Origin *;
		}

        #location /sf {
        #    error_page 418 = @server_main_proxy; return 418;
        #}

		#location / {
        #    error_page 418 = @server_main_proxy; return 418;
        #}

		location /static/ {
			alias /var/www/storagon/static/;
			limit_rate_after 1m;
			limit_rate 100k;
			access_log off;
			add_header Access-Control-Allow-Origin *;
		}
		
		location /media/ {
			alias /var/www/storagon/media/;
			internal;
			sendfile on;
			limit_rate 500k;
			limit_conn one 2;
			access_log  /var/log/nginx/traffic.log xfs;
			add_header Access-Control-Allow-Origin *;
		}
		
		location /nolimit/media/ {
			alias /var/www/storagon/media/;
			internal;
			sendfile on;
			limit_rate 6000k;
			limit_conn one 100;
			access_log  /var/log/nginx/traffic.log xfs;
			add_header Access-Control-Allow-Origin *;

		}

		location /direct/media/ {
			alias /var/www/storagon/media/;

			satisfy any;
			auth_basic           "closed site";
			auth_basic_user_file /var/www/conf/htpasswd.txt;

			limit_conn one 100;
			#access_log  /var/log/nginx/traffic.log xfs;
			add_header Access-Control-Allow-Origin *;

		}

		#error_page  404			  /404.html;

		# redirect server error pages to the static page /50x.html
		#
		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   html;
		}

	}

}
